### ISSUE TITLE
DOC: What does the 'type' column mean?

### ISSUE THREAD

**Issue by hhzl** [FarbodSalamat-Zadeh/FlashcardsApp#24]
For example in
https://github.com/FarbodSalamat-Zadeh/FlashcardsApp/blob/master/app/src/main/assets/fr_aqa_13-colours.csv

**Comment by farbodsz** [comment]
It's the tier of the vocabulary from the AQA specification.

0 means general vocabulary, 1 means foundation tier, and 2 means higher tier.

(See [LanguagesFlashCard.java](https://github.com/FarbodSalamat-Zadeh/FlashcardsApp/blob/master/app/src/main/java/com/satsumasoftware/flashcards/framework/flashcard/LanguagesFlashCard.java#L34))

I never got round to adding the other vocabulary, and since I didn't need the app after my exams, I never had a chance to complete the vocabulary and information lists.

**Comment by hhzl** [comment]
Thanks, and where does the data come from?

Link in
http://www.aqa.org.uk ?

**Comment by farbodsz** [comment]
@hhzl The data comes from two booklets by Nelson Thornes Ltd - I've put the links for them here:

http://mcsmodlangs.org/French_GCSE_files/AQA%20GCSE%20French%20vocab.pdf
https://spanishatstmalachys.wikispaces.com/file/view/span_gcse_vocab_list.pdf/290033145/span_gcse_vocab_list.pdf

**Comment by farbodsz** [comment]
Reopen if you have any other questions.

I'll see if I can add documentation in the coming months, or you can contribute via a pull request if you prefer (see #14 ).
